// ============================================================================
// ShortVoice -- FROZEN SCHEMA CONTRACT
// ============================================================================
// This file lives on `main` and is the shared contract for Persons A/B/C/D.
// DO NOT edit this file on a feature branch. If you genuinely need a field,
// message Person E (integrator); E lands it on `main` and everyone rebases.
// Every merge conflict at 5pm traces back to somebody editing this file.
// ============================================================================

import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

// text-embedding-3-small -> 1536 dims. If you change the embedding model,
// you change this number, and every stored vector must be regenerated.
export const EMBEDDING_DIMENSIONS = 1536;

// The set of things ShortVoice can actually DO. Adding a member here means
// adding an executor in convex/executors.ts (network) or mcp/localActions.ts (OS).
export const actionType = v.union(
  v.literal("send_message"), // iMessage / SMS -- local, AppleScript
  v.literal("send_slack"), // Slack -- network, Convex action
  v.literal("create_event"), // Calendar -- local, AppleScript
  v.literal("read_screen"), // describe what's on screen -- local
  v.literal("focus_mode"), // DND + close apps + timer -- local
  v.literal("open_app"), // launch/focus an app -- local
  v.literal("web_search"), // flights, lookups -- network
  v.literal("place_call"), // ShortVoice phones a business on your behalf -- network
  v.literal("apply_job"), // find roles and submit an application -- network
  v.literal("speak"), // just say something back
  v.literal("custom"), // freeform intent handed back to VoiceOS
);

export default defineSchema({
  // --------------------------------------------------------------------------
  // Who is speaking. One row for the demo; keyed by handle "demo".
  // --------------------------------------------------------------------------
  users: defineTable({
    name: v.string(),
    handle: v.string(), // "demo"
    // Deepgram aura-2 voice used for ShortVoice's own confirmation channel.
    voiceModel: v.string(), // e.g. "aura-2-thalia-en"
    createdAt: v.number(),
  }).index("by_handle", ["handle"]),

  // --------------------------------------------------------------------------
  // THE PERSONAL LANGUAGE. Each row is one word/phrase this person has taught.
  // --------------------------------------------------------------------------
  phrases: defineTable({
    userId: v.id("users"),

    trigger: v.string(), // as spoken: "school mom"
    normalizedTrigger: v.string(), // lowercased, punctuation-stripped, tokens sorted
    embedding: v.array(v.float64()), // 1536 dims, of `trigger` + intentTemplate

    // The full natural-language intent this phrase expands into.
    // Slots are written as {curly} placeholders: "Text Mom that I'll be there at {time}"
    intentTemplate: v.string(),

    actionType,
    params: v.any(), // executor-specific, e.g. { contact: "Mom", body: "..." }
    slots: v.array(v.string()), // slot names fillable from leftover words: ["time"]

    source: v.union(
      v.literal("taught"), // user said "when I say X it means Y"
      v.literal("suggested"), // system proposed it, user accepted
      v.literal("seeded"), // demo seed data
    ),

    useCount: v.number(),
    lastUsedAt: v.optional(v.number()),
    active: v.boolean(),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_user_trigger", ["userId", "normalizedTrigger"])
    .index("by_user_active", ["userId", "active"])
    .vectorIndex("by_embedding", {
      vectorField: "embedding",
      dimensions: EMBEDDING_DIMENSIONS,
      filterFields: ["userId", "active"],
    }),

  // --------------------------------------------------------------------------
  // Who "Mom" / "Neel" / "the team" actually are.
  // --------------------------------------------------------------------------
  contacts: defineTable({
    userId: v.id("users"),
    alias: v.string(), // "mom" (lowercased)
    fullName: v.string(), // "Rashmi"
    phone: v.optional(v.string()),
    slackId: v.optional(v.string()), // Slack channel or user id
    email: v.optional(v.string()),
  }).index("by_user_alias", ["userId", "alias"]),

  // --------------------------------------------------------------------------
  // CONFIRMATION STATE MACHINE. Nothing consequential fires without passing
  // through here. At most one row per user should be "awaiting".
  // --------------------------------------------------------------------------
  pendingActions: defineTable({
    userId: v.id("users"),
    utterance: v.string(), // "school mom"
    phraseId: v.optional(v.id("phrases")),

    resolvedIntent: v.string(), // "Text Mom that you're leaving school and heading home"
    confirmationSpeech: v.string(), // "Texting Mom that you're heading home. Yes?"

    actionType,
    params: v.any(),
    matchScore: v.optional(v.number()), // cosine score from vector search

    status: v.union(
      v.literal("awaiting"),
      v.literal("confirmed"),
      v.literal("cancelled"),
      v.literal("executed"),
      v.literal("failed"),
    ),
    result: v.optional(v.string()), // what the executor reported
    createdAt: v.number(),
    resolvedAt: v.optional(v.number()),
  })
    .index("by_user_status", ["userId", "status"])
    .index("by_user", ["userId"]),

  // --------------------------------------------------------------------------
  // Every utterance ever heard. This is the training data for auto-suggest.
  // --------------------------------------------------------------------------
  utterances: defineTable({
    userId: v.id("users"),
    raw: v.string(),
    resolvedIntent: v.optional(v.string()),
    matchedPhraseId: v.optional(v.id("phrases")),
    matchScore: v.optional(v.number()),
    embedding: v.optional(v.array(v.float64())),
    outcome: v.union(
      v.literal("matched"), // hit an existing taught phrase
      v.literal("expanded"), // no phrase, LLM expanded from context
      v.literal("unresolved"), // we did not understand
      v.literal("taught"), // this utterance was a teaching command
    ),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .vectorIndex("by_embedding", {
      vectorField: "embedding",
      dimensions: EMBEDDING_DIMENSIONS,
      filterFields: ["userId"],
    }),

  // --------------------------------------------------------------------------
  // AUTO-SUGGEST -- "you've asked for that three times, want a word for it?"
  // This is the feature that proves ShortVoice is a language, not macros.
  // --------------------------------------------------------------------------
  suggestions: defineTable({
    userId: v.id("users"),
    proposedTrigger: v.string(), // "standup"
    intentTemplate: v.string(),
    actionType,
    params: v.any(),
    evidenceCount: v.number(), // how many similar utterances triggered this
    evidenceUtterances: v.array(v.string()),
    status: v.union(
      v.literal("pending"),
      v.literal("accepted"),
      v.literal("dismissed"),
    ),
    createdAt: v.number(),
  }).index("by_user_status", ["userId", "status"]),

  // --------------------------------------------------------------------------
  // OUTBOUND PHONE CALLS (a1mobile).
  //
  // "appointment dentist" is three words that turn into a real phone call:
  // ShortVoice dials the business and talks to whoever answers on the user's
  // behalf. This table is the shared state between the two halves of that,
  // because they run in different places. `telephony.startCall` writes the row
  // and asks a1mobile to dial; a1mobile then POSTs our public /voice webhook on
  // answer, and that request has no memory of why the call was placed. It finds
  // this row to learn what it is supposed to say.
  // --------------------------------------------------------------------------
  calls: defineTable({
    userId: v.id("users"),

    to: v.string(), // E.164 destination
    business: v.string(), // "the dentist"
    purpose: v.string(), // "book a check-up appointment"

    // Everything the agent is allowed to say on the user's behalf. Kept as an
    // explicit brief rather than a free prompt so the call cannot invent
    // commitments the user never made.
    brief: v.object({
      callerName: v.string(),
      callbackNumber: v.string(),
      preferredWindow: v.string(), // "sometime next week, mornings"
      reason: v.string(), // "routine check-up and cleaning"
    }),

    status: v.union(
      v.literal("dialing"),
      v.literal("in_progress"),
      v.literal("completed"),
      v.literal("failed"),
    ),

    // Grows one entry per webhook turn. Rendered live on the dashboard, which
    // is what makes the call visible to a room that can only hear one side.
    transcript: v.array(
      v.object({
        role: v.union(v.literal("agent"), v.literal("them")),
        text: v.string(),
        at: v.number(),
      }),
    ),

    outcome: v.optional(v.string()), // "Booked Tuesday 9:30am"
    providerCallId: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_user", ["userId"])
    .index("by_status", ["status"]),

  // --------------------------------------------------------------------------
  // LIVE DEMO FEED. Every stage of the pipeline writes here; the dashboard
  // subscribes and animates it in real time. This is how Convex reactivity
  // becomes visible on the projector.
  // --------------------------------------------------------------------------
  events: defineTable({
    userId: v.id("users"),
    kind: v.union(
      v.literal("heard"), // raw speech in
      v.literal("resolved"), // compressed -> full intent
      v.literal("awaiting"), // asked for confirmation
      v.literal("confirmed"),
      v.literal("cancelled"),
      v.literal("executed"),
      v.literal("taught"), // new phrase learned
      v.literal("suggested"), // system proposed a new word
      v.literal("error"),
    ),
    text: v.string(),
    detail: v.optional(v.any()),
    latencyMs: v.optional(v.number()),
    createdAt: v.number(),
  }).index("by_user", ["userId"]),
});
